# Generated by Django 3.0.8 on 2020-09-04 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yash', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='photo',
            field=models.ImageField(upload_to='city_images/'),
        ),
        migrations.AlterField(
            model_name='statemodel',
            name='photo',
            field=models.ImageField(upload_to='state_images/'),
        ),
    ]
