# Generated by Django 3.0.8 on 2020-09-04 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yash', '0002_auto_20200904_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateModel1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='state_images/')),
            ],
        ),
        migrations.AlterField(
            model_name='citymodel',
            name='city_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yash.StateModel1'),
        ),
        migrations.DeleteModel(
            name='StateModel',
        ),
    ]
