# Generated by Django 3.0.8 on 2020-09-07 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yash', '0003_auto_20200904_1530'),
    ]

    operations = [
        migrations.CreateModel(
            name='CityModel1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('photo', models.ImageField(upload_to='city_images/')),
            ],
        ),
        migrations.RemoveField(
            model_name='citymodel',
            name='city_state',
        ),
    ]
