# Generated by Django 3.0.8 on 2020-09-07 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yash', '0004_auto_20200907_2227'),
        ('customer', '0002_auto_20200907_2227'),
        ('vendor', '0002_auto_20200907_2227'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CityModel',
        ),
        migrations.AddField(
            model_name='citymodel1',
            name='city_state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yash.StateModel1'),
        ),
    ]
